export const products = [
	{
		id: 1,
		title: "Office Setup",
		image: "/images/home-office/flower.jpg",
		price: "₦150,000",
		description: "A complete office setup with ergonomic furniture and décor.",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 2,
		title: "Modern Lamp",
		image: "/images/home-office/office-lamp.jpg",
		price: "₦25,000",
		description: "A sleek and modern office lamp with adjustable brightness.",
		shippingInfo: ["Ships within 2-4 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 3,
		title: "Stylish Office Chair",
		image: "/images/home-office/officechair.jpg",
		price: "₦45,000",
		description:
			"Ergonomic office chair with lumbar support and adjustable height.",
		shippingInfo: ["Ships within 3-6 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 4,
		title: "Wall Clock",
		image: "/images/home-office/clock.jpg",
		price: "₦10,000",
		description: "Minimalist wall clock with silent movement technology.",
		shippingInfo: ["Ships within 1-3 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 5,
		title: "Living Room Setup",
		image: "/images/home-office/tv.jpg",
		price: "₦200,000",
		description:
			"A luxurious living room setup with a high-end entertainment unit.",
		shippingInfo: ["Ships within 4-7 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 6,
		title: "Flower Pot",
		image: "/images/home-office/pot-of-flower.jpg",
		price: "₦5,000",
		description: "Beautiful decorative flower pot for home or office use.",
		shippingInfo: ["Ships within 2-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
];
