export const products = [
	{
		id: 1,
		title: "Motherboard",
		image: "/images/electronics/motherboard.jpg",
		price: "₦200,000",
		description: "High-end motherboard for gaming",
		shippingInfo: ["Ships within 3-6 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days of purchase",
	},
	{
		id: 2,
		title: "Roland Drumkit",
		image: "/images/electronics/drumkit.jpg",
		price: "₦120,000",
		description: "Professional electronic drumkit",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 3,
		title: "Apple Keyboard",
		image: "/images/electronics/keyboard.jpg",
		price: "₦40,000",
		description: "Sleek Apple wireless keyboard",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 4,
		title: "Microphone",
		image: "/images/electronics/microphone.jpg",
		price: "₦80,000",
		description: "High-fidelity studio microphone",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 5,
		title: "RED Camera",
		image: "/images/electronics/camera.jpg",
		price: "₦500,000",
		description: "Professional 4K RED camera",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 5,
		title: "Motherboard",
		image: "/images/electronics/motherboard.jpg",
		price: "₦200,000",
		description: "High-end motherboard for gaming",
		shippingInfo: ["Ships within 3-6 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days of purchase",
	},
];