export const products = [
	{
		id: 1,
		title: "🎾 Tennis Equipment",
		image: "/images/games/tennis.jpg",
		price: "₦50,000",
		description: "Premium rackets and accessories for all skill levels.",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days of purchase",
	},
	{
		id: 2,
		title: "⚽ Football Gear",
		image: "/images/games/football.jpg",
		price: "₦30,000",
		description: "High-quality footballs, boots, and training gear.",
		shippingInfo: ["Ships within 2-4 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 3,
		title: "🏀 Basketball Equipment",
		image: "/images/games/basketball.jpg",
		price: "₦40,000",
		description: "Professional basketballs, hoops, and accessories.",
		shippingInfo: ["Ships within 3-6 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 4,
		title: "🎮 PlayStation 5",
		image: "/images/games/ps5.jpg",
		price: "₦700,000",
		description: "Sony’s next-gen gaming console for ultimate gameplay.",
		shippingInfo: ["Ships within 5-7 days"],
		paymentInfo: "Online payment only",
		returnInfo: "Return within 7 days if unopened",
	},
	{
		id: 5,
		title: "🕹️ Handheld Gaming Consoles",
		image: "/images/games/handgame.jpg",
		price: "₦80,000",
		description: "Portable consoles for gaming on the go.",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 6,
		title: "🏓 Table Tennis Set",
		image: "/images/games/table-tennis.jpg",
		price: "₦25,000",
		description: "Complete table tennis setup for home and competition.",
		shippingInfo: ["Ships within 2-4 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 7,
		title: "🎳 Bowling Equipment",
		image: "/images/games/bowling.jpg",
		price: "₦100,000",
		description: "Premium bowling balls and accessories.",
		shippingInfo: ["Ships within 4-6 days"],
		paymentInfo: "Online payment only",
		returnInfo: "Return within 7 days if unused",
	},
	{
		id: 8,
		title: "🎮 Gaming Controllers",
		image: "/images/games/gamepad.jpg",
		price: "₦35,000",
		description: "High-performance controllers for PlayStation, Xbox & PC.",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
	{
		id: 9,
		title: "🕹️ Classic Game Cartridges",
		image: "/images/games/sonic-game.jpg",
		price: "₦20,000",
		description: "Relive nostalgic gaming moments with classic titles.",
		shippingInfo: ["Ships within 3-5 days"],
		paymentInfo: "Cash on delivery or online payment",
		returnInfo: "Return within 7 days",
	},
];
